### ISSUE TITLE
find QuestionType strings in previous code and repalce with call to enum

### ISSUE THREAD

**Issue by tobydragon** [tobydragon/wizard#15]
We're looking for "parsons" and "activecode" hardcoded somewhere (maybe multiple locations). Find them and replace them with a constant in RunestoneStrings, and then have that constant reference QuestionType.getLogString()

**Comment by cwormsl2** [comment]
Found "parsons" and "mChoice" hardcoded in CfPropertyParser and replaced with a constant from RunestoneStrings

Didn't find an instance of "activecode" hardcoded anywhere
