### ISSUE TITLE
System should allow optional fields for cfActions

### ISSUE THREAD

**Issue by tobydragon** [tobydragon/wizard#19]
Not every analysis cfAction should be required to have all fields, since not all are applicable to all analysis, and this invites backwards compatibility.  We need to understand what happens when a field is missing, and consider how to implement it during creation.

For example, in perUserPerProblem, isCorrect is defaulted to true for non-assessable items (as stated in perUserAllProblems constructor.  HOwever, this is not correct, the isCorrect field should not exist for these items, as something not assessable should be neither correct nor incorrect.

**Comment by cwormsl2** [comment]
I created the separate assessable classes for PerUserPerProblem and AllUsersPerProblems which was sparked by this issue but I don't know if that solves what you were initially thinking when you created this.
