### ISSUE TITLE
Create a ConceptGraph from book info

### ISSUE THREAD

**Issue by tobydragon** [tobydragon/wizard#9]
will require:
  - make runestonetext classes implement  Concept interface
  - make a main class (maybe ConceptGraphTest?) that creates a Book (like BookTest) and then creates a ConceptGraph based on the book that has leaf nodes with proper question ids
  - make toString for ConceptNode that allows the tree to pretty print

**Comment by tobydragon** [comment]
introduce recursion and return a string from toString rather than calling System.out.

**Comment by cwormsl2** [comment]
toString now uses recursion to return a string
